name: Deploy Portfolio to Azure VM

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t myportfolio:v1 .

      - name: SCP Dockerfile and Files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.AZURE_VM_USER }}/portfolio"

      - name: SSH into Azure VM and run Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd portfolio
            docker stop myportfolio || true
            docker rm myportfolio || true
            docker build -t myportfolio:v1 .
            docker run -d -p 80:80 --name myportfolio myportfolio:v1
